export const category_data = [
  {
    title: "Graphic & Design",
    cat: [
      "Logo Design",
      "Brand Style Guide",
      "Brand Style Guide",
      "Brand Style Guide",
      "Brand Style Guide",
      "Brand Style Guide",
      "Brand Style Guide",
      "Brand Style Guide",
    ],
  },
  {
    title: "Digitel Marketing",
    cat: [
      "Social Media Marketing",
      "Social Media Advertising",
      "Social Media Marketing",
      "Social Media Advertising",
      "Social Media Marketing",
      "Social Media Advertising",
      "Social Media Marketing",
      "Social Media Advertising",
    ],
  },
  {
    title: "Writing & Translation",
    cat: [
      "Translation",
      "Cover Latter",
      "Translation",
      "Cover Latter",
      "Translation",
      "Cover Latter",
      "Translation",
      "Cover Latter",
      "Translation",
    ],
  },
  {
    title: "Video & Animation",
    cat: [
      "video Editing",
      "Visual Effects",
      "video Editing",
      "Visual Effects",
      "video Editing",
      "Visual Effects",
      "video Editing",
      "Visual Effects",
    ],
  },
  {
    title: "Music & Audio",
    cat: [
      "Voice Over",
      "Song Writter",
      "Voice Over",
      "Song Writter",
      "Voice Over",
      "Song Writter",
      "Voice Over",
      "Song Writter",
    ],
  },
  {
    title: "Programming & Tech",
    cat: [
      "Wordpress",
      "E-commerce",
      "Wordpress",
      "E-commerce",
      "Wordpress",
      "E-commerce",
      "Wordpress",
      "E-commerce",
      "Wordpress",
    ],
  },
  {
    title: "Business",
    cat: [
      "Market Research",
      "Sales",
      "Market Research",
      "Sales",
      "Market Research",
      "Sales",
      "Market Research",
      "Sales",
    ],
  },
  {
    title: "Lifestyle",
    cat: [
      "Online Tutoring",
      "Gaming",
      "Online Tutoring",
      "Gaming",
      "Online Tutoring",
      "Gaming",
      "Online Tutoring",
    ],
  },
];
